version: '3'
services:
  sql: 
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123%
      - SQL_PID=Standard
    ports:
      - "1434:1433"
    networks:
      - network
      
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672" # ui
    networks:
      - network
    
  index:
    image: elasticsearch:alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - network

  graylog:
    image: graylog/graylog:2.4.0-1
    environment:
      - GRAYLOG_PASSWORD_SECRET=GRAYLOG_PASSWORD_SECRET
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"     # ui
    networks:
      - network

  mongo:
    image: mongo:3
    networks:
      - network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network

networks:
  network:
    driver: bridge