version: '3'
services:

  neptune.app.web:
    image: neptune.app.web
    build:
      context: .
      dockerfile: Apps/Web/Neptune.Apps.Web/Dockerfile
    ports:
      - "80:80"
    networks:
      - neptune_network

  neptune.apps.webapi:
    image: neptune.apps.webapi
    build:
      context: .
      dockerfile: Apps/WebAPI/Neptune.Apps.WebAPI/Dockerfile
    ports:
      - "81:80"
    networks:
      - neptune_network

  neptune.services.databases:
    image: neptune.services.databases
    build:
      context: .
      dockerfile: Services/Databases/Neptune.Services.Databases/Dockerfile
    networks:
      - neptune_network

  neptune.services.profiles:
    image: neptune.services.profiles
    build:
      context: .
      dockerfile: Services/Profiles/Neptune.Services.Profiles/Dockerfile
    networks:
      - neptune_network

  neptune.services.questions:
    image: neptune.services.questions
    build:
      context: .
      dockerfile: Services/Questions/Neptune.Services.Questions/Dockerfile
    networks:
      - neptune_network

  neptune.services.identities:
    image: neptune.services.identities
    build:
      context: .
      dockerfile: Services/Identities/Neptune.Services.Identities/Dockerfile
    networks:
      - neptune_network

networks:
  neptune_network:
    external: true

